<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV3PNJfy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV3PNJfy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerV3PNJfy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerV3PNJfy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerV3PNJfy\App_KernelDevDebugContainer([
    'container.build_hash' => 'V3PNJfy',
    'container.build_id' => 'e1affa74',
    'container.build_time' => 1645402593,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV3PNJfy');
